title: Ivan Zichtl.  # name of the site
author: Ivan Zichtl # name of site's author
email: izichtl@gmail.com # email of site's author
url: https://quemsoueu.netlify.app # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: "Desenvolvedor NodeJs." # description of the site (multiple lines allowed)


permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "izichtl" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  back_all_text: "Todos os projetos" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y-" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
